#!/usr/bin/env python

#=======================================================================================================================
# PyClone
# Author : Andrew Roth
#=======================================================================================================================
import argparse

from pyclone.run import build_prior_file, cluster_trace, plot_cellular_frequencies, plot_similarity_matrix, run_dp_model

parser = argparse.ArgumentParser(prog='PyClone')

parser.add_argument('--version', action='version', version='PyClone-0.10.0-b1')

subparsers = parser.add_subparsers()

#---------------------------------------------------------------------------------------------------------------------- 
analyse_parser = subparsers.add_parser('analyse', help='''Start a new PyClone analysis.''')

analyse_parser.add_argument('in_file',
                            help='Path to tab separated input file. See examples for format.')

analyse_parser.add_argument('out_dir',
                            help='Path where trace files for MCMC sampler will be written.')

analyse_parser.add_argument('--num_iters', default=10000, type=int,
                            help='''How many iterations of the MCMC chain will run. Default 10,000.''')

analyse_parser.add_argument('--concentration', default=None, type=int,
                            help='''Concentration (alpha) value for DP sampler. If not set it will be estimated. Default
                            estimated.''')

analyse_parser.add_argument('--tumour_content', default=1, type=float,
                            help='''The fraction of the cancer cells in the sample. Default 1.''')

analyse_parser.add_argument('--seed', default=None, type=int,
                            help='''Set random seed so results can be reproduced. By default a random seed is
                            chosen.''')

analyse_parser.add_argument('--concentration_prior_shape', default=1, type=float,
                            help='''Prior on the shape parameter in the prior for the concentration parameter. Default
                            1.''')

analyse_parser.add_argument('--concentration_prior_rate', default=1, type=float,
                            help='''Prior on the rate parameter in the prior for the concentration parameter. Default
                            1.''')

analyse_parser.add_argument('--error_rate', default=1e-3, type=float,
                            help='''Error rate of sequencing. Default 1e-3.''')

analyse_parser.set_defaults(func=run_dp_model)

#---------------------------------------------------------------------------------------------------------------------- 
build_prior_parser = subparsers.add_parser('build_prior', help='''Build an input file for PyClone analysis.''')

build_prior_parser.add_argument('in_file',
                                help='Path to tab separated input file. See examples for format.')

build_prior_parser.add_argument('out_file',
                                help='Path where PyClone formatted input file will be written.')

build_prior_parser.add_argument('--error_rate', default=1e-3, type=float,
                                help='''Estimated sequencing error rate. This should match the value used in subsequent
                                PyClone analysis. Default 1e-3.''')

build_prior_parser.add_argument('--cn_r', choices=['normal', 'variant', 'vague'], default='vague',
                                help='''Method for setting the copy number of the reference population. "normal" sets it
                                to 2 (copy number of normal). "variant" sets it to the value of "cn" in the input file
                                row (copy number of the variant population). "vague" considers both options with equal
                                prior weight. Default vague.''')

build_prior_parser.add_argument('--mu_v', choices=['single', 'all', 'vague'], default='vague',
                                help='''Method used to set mu_v parameter which is determined by the assume genotype of
                                the variant population. "single" assumes the variant population has the genotype with
                                one variant allele. "all" assumes the variant population has the genotype with all
                                variant alleles. "vague" considers all genotypes compatible with the predicted copy
                                number assigning equal weights. Default is vague.''')

build_prior_parser.set_defaults(func=build_prior_file)

#---------------------------------------------------------------------------------------------------------------------- 
cluster_parser = subparsers.add_parser('cluster', help='''Cluster the results of a PyClone analysis.''')

cluster_parser.add_argument('trace_dir',
                            help='Path to directory where the PyClone analysis trace was written.')

cluster_parser.add_argument('out_file',
                            help='Path to file where clustering results will be written.')

cluster_parser.add_argument('--method', default='mpear',
                            choices=['affinity_propogation', 'complete_linkage', 'dbscan', 'dynamic_tree_cut', 'mpear',
                                    'single_linkage', 'spectral_clustering'],
                            help='''Method used to cluster the PyClone trace file. Default is mpear.''')

cluster_parser.add_argument('--burnin', default=0, type=int,
                            help='''Number of samples to discard as burning for the MCMC chain. Default is 0.''')

cluster_parser.add_argument('--thin', default=1, type=int,
                            help='''Number of samples to thin MCMC trace. For example if thin=10 every tenth sample
                            after burning will be used for inference. Default is 1.''')

cluster_parser.set_defaults(func=cluster_trace)

#---------------------------------------------------------------------------------------------------------------------- 
plot_cf_parser = subparsers.add_parser('plot_cellular_frequencies',
                                       help='''Plot the posterior densities of the cellular frequencies of the mutations
                                       from a PyClone analysis.''')

plot_cf_parser.add_argument('trace_dir',
                            help='Path to directory where the PyClone analysis trace was written.')

plot_cf_parser.add_argument('out_file',
                            help='Path to file where plot will be saved.')

plot_cf_parser.add_argument('--burnin', default=0, type=int,
                            help='''Number of samples to discard as burning for the MCMC chain. Default is 0.''')

plot_cf_parser.add_argument('--thin', default=1, type=int,
                            help='''Number of samples to thin MCMC trace. For example if thin=10 every tenth sample
                            after burning will be used for inference. Default is 1.''')

plot_cf_parser.set_defaults(func=plot_cellular_frequencies)

#---------------------------------------------------------------------------------------------------------------------- 
plot_sm_parser = subparsers.add_parser('plot_similarity_matrix',
                                       help='''Plot a heat map of the posterior similarity matrix from a PyClone
                                       analysis.''')

plot_sm_parser.add_argument('trace_dir',
                            help='Path to directory where the PyClone analysis trace was written.')

plot_sm_parser.add_argument('out_file',
                            help='Path to file where plot will be saved.')

plot_sm_parser.add_argument('--burnin', default=0, type=int,
                            help='''Number of samples to discard as burning for the MCMC chain. Default is 0.''')

plot_sm_parser.add_argument('--thin', default=1, type=int,
                            help='''Number of samples to thin MCMC trace. For example if thin=10 every tenth sample
                            after burning will be used for inference. Default is 1.''')

plot_sm_parser.set_defaults(func=plot_similarity_matrix)

#---------------------------------------------------------------------------------------------------------------------- 

analyse_parser.set_defaults(func=run_dp_model)

args = parser.parse_args()

args.func(args)
