#!/usr/bin/env python

#=======================================================================================================================
# PyClone
# Author : Andrew Roth
#=======================================================================================================================
import argparse

from pyclone.run import run_dp_model 

parser = argparse.ArgumentParser(prog='PyClone')

parser.add_argument('in_file_name',
                    help='Path to tab separated input file. See examples for format.')

parser.add_argument('out_file_name',
                    help='Path where output will be written.')

parser.add_argument('--num_iters', default=10000, type=int,
                    help='''How many iterations the MCMC chain will run. Default is 10,000.''')

parser.set_defaults(func=run_dp_model)

args = parser.parse_args()

args.func(args)
